"""Add deleted_at column to all models

Revision ID: 03fc98ea0f3a
Revises: 32ab8cfdd2ef
Create Date: 2025-03-03 10:30:06.702681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03fc98ea0f3a'
down_revision = '32ab8cfdd2ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dreams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('dreams', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
